name: Bug Report
description: Report an rrweb web extension bug
title: '[Bug]: '
labels:
  - 'bug'
body:
  - type: input
    attributes:
      label: Version
      description: What's the version of the package?
      placeholder: v1.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happens.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe detailed steps for reproducing the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: If your problem needs further explanation, or if the issue you're seeing cannot be reproduced in a gist, please add more information here.
